spring:
  main:
    banner-mode: off
  profiles:
    active: local
  datasource:
    url:
    username:
    password:
    hikari:
      max-lifetime: 600000
      connectionTimeout: 5000
      maximumPoolSize: 50
      minimumIdle: 5
      idleTimeout: 30000
      leak-detection-threshold: 120000
      test-while-idle: true
      test-on-borrow: true
  jpa:
    database-platform:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 350
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: false
        show_sql: false
        format_sql: false

server:
  host: localhost
  port: 8080
  tomcat:
    basedir: tmp
    threads:
      max: 300
  servlet:
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
    com:
      zaxxer:
        hikari:
          HikariConfig: INFO
          pool:
            HikariPool: INFO

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
      show-details: always
